### ISSUE TITLE
timezone from nil (etz:"Asia/India",tnz:"Asi",tzid:"constant") (ArgumentError)

### ISSUE THREAD

**Issue by jmettraux** [jmettraux/rufus-scheduler#240]
See http://stackoverflow.com/questions/42375399/windows-rufus-envtz-continent-city-error

tnz: "Asi"?

**Comment by riddley** [comment]
Hi John,

Long time no chat! I hope you're well.

I'm seeing this too post-DST on Debian Stretch. I worked around it by setting the ENV, but thought I should report it. rufus-scheduler (3.3.4)

Here's the exact error:

```
/var/lib/gems/2.3.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/zotime.rb:41:in `initialize': cannot determine timezone from nil (etz:nil,tnz:"EDT",tzid:nil) (ArgumentError)
```

**Comment by kenpropel** [comment]
Here in CA, USA. Similar problem.

```/usr/local/rvm/gems/ruby-2.1.10@eda/gems/rufus-scheduler-3.3.2/lib/rufus/scheduler/zotime.rb:41:in `initialize': cannot determine timezone from nil (etz:nil,tnz:"PDT",tzid:nil) (ArgumentError)```

**Comment by jmettraux** [comment]
Yes, "PDT" and "EDT" are not helping at all.

As a reminder, for future readers: https://github.com/jmettraux/rufus-scheduler#i-get-zotimerb41in-initialize-cannot-determine-timezone-from-nil

I think I will make sure that rufus-scheduler 3.4.0 works with a "I don't care timezone" for those cases. Or I should try harder to determine the timezone... Rails has it easy, they go for UTC by default.

**Comment by riddley** [comment]
FWIW, the tzinfo-data gem instructions didn't fix the problem for me. I went with 

```ruby
ENV['TZ'] = File.read('/etc/timezone').strip
```

Which I understand won't work for everyone.

**Comment by jmettraux** [comment]
For CentOS, I could read `/etc/sysconfig/clock` and if I find a similar technique for OSX as well, that covers a lot of cases...

@riddley thanks for the idea

**Comment by jmettraux** [comment]
Would one of you @riddley @kenpropel or @varyonic have the time to test what I just pushed. Tell me if it works or not on your system and what your system is (Debian, CentOS, OSX, Win, ...)

Thanks in advance.

**Comment by kenpropel** [comment]
The patch seems to be working; I didn't get the error. My system would fall under Debian.

`Linux 4.4.0-66-generic #87~14.04.1-Ubuntu SMP Fri Mar 3 17:32:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jmettraux** [comment]
@riddley I hope you are well too, I'm happy to chat again with you.

**Comment by veetow** [comment]
@jmettraux, I'm having the same issue after the Daylight Saving switch.  I tried your patch in commit ffbb3de6f17bba827b5da6abd0ab770b7e7bcf6a, but I'm still getting a similar error:

```
/opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/zotime.rb:41:in `initialize': cannot determine timezone from "EDT" (etz:nil,tnz:"EDT",tzid:nil,rv:"2.1.2",rp:"x86_64-linux",stz:(debian:nil,centos:"America/New_York",osx:nil))  (ArgumentError)
Try setting `ENV['TZ'] = 'Continent/City'` in your script (see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) and adding 'tzinfo-data' to your gems
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/zotime.rb:447:in `new'
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/zotime.rb:447:in `make'
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/jobs.rb:448:in `first_at='
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/jobs.rb:539:in `first_at='
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/jobs.rb:431:in `initialize'
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/jobs.rb:549:in `initialize'
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler.rb:639:in `new'
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler.rb:639:in `do_schedule'
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler.rb:225:in `every'
        from /opt/poe/lib/poe/ipam/service.rb:60:in `enable_schema_broadcasts'
        from /opt/poe/lib/poe/ipam/service.rb:40:in `run'
        from ./bin/ipam-service:8:in `<main>'
```

**Comment by jmettraux** [comment]
@veetow Hello, why do you think it's related to the Daylight switch? Are you actually restarting your rufus-scheduler every day?

**Comment by veetow** [comment]
@jmettraux my app was deployed and running fine before the switch, but deployed to another server after the switch and with updated tzdata RPM, and I started having the issue.

**Comment by jmettraux** [comment]
> Perhaps the issue is that there isn't an exact match for EDT in the zoneinfo?

@veetow Yes, those `XXX` timezone abbreviations are ambiguous.

The error message is indicating that you have not "tzinfo-data" present in your gems. Could you please add it and try again?

Thanks in advance.

**Comment by veetow** [comment]
I didn't try that yet as the hosts in question don't have internet access.  I can say that setting `ENV['TZ'] = 'UTC'` works fine.

**Comment by veetow** [comment]
Adding the gem didn't help.

```
/opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/zotime.rb:41:in `initialize': cannot determine timezone from "EDT" (etz:nil,tnz:"EDT",tzid:"constant",rv:"2.1.2",rp:"x86_64-linux",stz:(debian:nil,centos:"America/New_York",osx:"EST5EDT"))  (ArgumentError)
Try setting `ENV['TZ'] = 'Continent/City'` in your script (see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/zotime.rb:447:in `new'
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/zotime.rb:447:in `make'
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/jobs.rb:448:in `first_at='
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/jobs.rb:539:in `first_at='
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/jobs.rb:431:in `initialize'
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/jobs.rb:549:in `initialize'
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler.rb:639:in `new'
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler.rb:639:in `do_schedule'
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler.rb:225:in `every'
        from /opt/poe/lib/poe/ipam/service.rb:60:in `enable_schema_broadcasts'
        from /opt/poe/lib/poe/ipam/service.rb:40:in `run'
        from ./bin/ipam-service:8:in `<main>'
```

**Comment by jmettraux** [comment]
@veetown Does setting `ENV['TZ'] = 'America/New_York'` work?

**Comment by veetow** [comment]
No, it still says: `cannot determine timezone from "EDT"`.

**Comment by jmettraux** [comment]
OK, thanks a lot.

**Comment by jmettraux** [comment]
@veetow May I see what you have at line 60 (and around) of your `poe/ipam/service.rb` file?

(referring to the backtrace:
```
        from /opt/poe/lib/poe/ipam/service.rb:60:in `enable_schema_broadcasts'
```
)

Thanks in advance.

**Comment by veetow** [comment]
Sure thing.

```
# @scheduler = Rufus::Scheduler.new

def enable_schema_broadcasts
  @scheduler.every("1m", first_at: Time.now + 10) do
    # things
  end
end
```

**Comment by jmettraux** [comment]
@veetow does
```ruby
def enable_schema_broadcasts
  @scheduler.every("1m", first_in: '10s') do
    # things
  end
```
make the EDT error vanish?

**Comment by veetow** [comment]
@jmettraux it works!

**Comment by veetow** [comment]
As an aside, doing `:first => :now` also produces the error.

**Comment by jmettraux** [comment]
@veetow thanks a lot!

**Comment by veetow** [comment]
@jmettraux I was wrong, I'm sorry.  I must have had some cruft in my environment.  Using `first_in: '10s'` does not fix the issue.

**Comment by jmettraux** [comment]
@veetow what's the new error message and backtrace?

**Comment by veetow** [comment]
Same:

```
/opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/zotime.rb:41:in `initialize': cannot determine timezone from nil (etz:nil,tnz:"EDT",tzid:nil) (ArgumentError)
Try setting `ENV['TZ'] = 'Continent/City'` in your script (see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) and adding 'tzinfo-data' to your gems
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/zotime.rb:206:in `new'
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler/zotime.rb:206:in `now'
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler.rb:561:in `start'
        from /opt/poe/vendor/bundle/ruby/2.1.0/gems/rufus-scheduler-3.3.4/lib/rufus/scheduler.rb:109:in `initialize'
        from /opt/poe/lib/poe/ipam/service.rb:26:in `new'
        from /opt/poe/lib/poe/ipam/service.rb:26:in `initialize'
        from /opt/poe/lib/poe/ipam/service.rb:37:in `new'
        from /opt/poe/lib/poe/ipam/service.rb:37:in `run'
        from ./bin/ipam-service:8:in `<main>'
```

However, I this does work now whereas I had to use `UTC` before: `ENV['TZ'] = 'America/New_York'`

**Comment by veetow** [comment]
Creating this symlink also resolves the issue:

```
# ls -l /usr/share/zoneinfo/EDT 
lrwxrwxrwx 1 root root 27 Mar 21 16:50 /usr/share/zoneinfo/EDT -> /usr/share/zoneinfo/EST5EDT
```

**Comment by veetow** [comment]
And before the Daylight Saving switch, we likely didn't have the issue because the `EST` zoneinfo file exists:

```
# ls -l /usr/share/zoneinfo/EST
-rw-r--r-- 1 root root 118 Mar  8 16:33 /usr/share/zoneinfo/EST
```

**Comment by jmettraux** [comment]
@veetow but before the daylight saving switch, you were using a vanilla rufus-scheduler, not this experimental system tz detection version...

**Comment by veetow** [comment]
@jmettraux I'm not using your patch anymore.  I'm using `rufus-scheduler-3.3.4` from RubyGems.

**Comment by jmettraux** [comment]
(confused)

**Comment by veetow** [comment]
Maybe I am?  What is the "experimental system tz detection version"?

**Comment by jmettraux** [comment]
It's the patch you mention in https://github.com/jmettraux/rufus-scheduler/issues/240#issuecomment-287100934 I thought you were still using it.

**Comment by veetow** [comment]
Ah, no sorry.  I rebuilt my image and it pulls in version `3.3.4` of the gem.  Clearly that's the differentiator and not environment cruft like I was assuming.

**Comment by jmettraux** [comment]
OK. I'm currently reworking this tz setting code in a separate gem at https://github.com/floraison/et-orbi I hope to integrate it soon in rufus-scheduler. I hope you'll have time to check it out.

**Comment by jmettraux** [comment]
@veetow if you could test with what is currently on master and tell me how it behaves, I'd be extremely grateful :-)

**Comment by veetow** [comment]
Works!

**Comment by jmettraux** [comment]
Yes, I will try to release 3.4.0 today.

**Comment by jmettraux** [comment]
3.4.0 released, I'm closing this issue but feel free to report any problem (here for tz issues, new issue else).

Thanks!
